// GENERATED by scripts/generate-command-surface.mjs — do not edit.
// Run `npm run generate:command-surface -- --update` after a runtime bump.
//
// Derived from ACP_BUILTIN_SLASH_COMMANDS in the installed
// @gajae-code/coding-agent. Anything the runtime advertises appears here
// automatically; only the exclusions and additions below are hand-maintained.
//
// Excluded text builtins:
//   move: Retargets the session working directory, which desyncs the app-owned project binding. Answered by a local notice instead.

export type GjcAppCommand = {
  name: string;
  description: string;
  inputHint?: string;
};

export const GJC_APP_BUILTIN_COMMANDS: readonly GjcAppCommand[] = [
  { name: "aside", description: "Run the Aside CLI", inputHint: "[exec|repl|mcp|account|help|<prompt>]" },
  { name: "notify", description: "Notification status, health, test, recovery, and session on/off", inputHint: "[on|off|status|health|test|recovery|setup]" },
  { name: "model", description: "Show current model selection", inputHint: "[target] <model>" },
  { name: "effort", description: "Show or set model reasoning effort", inputHint: "[inherit|off|minimal|low|medium|high|xhigh|max]" },
  { name: "fast", description: "Toggle fast mode", inputHint: "[on|off|status]" },
  { name: "routing", description: "Show or set up sub-agent model autorouting", inputHint: "[on|off|status]" },
  { name: "export", description: "Export this session to an HTML file", inputHint: "[path]" },
  { name: "dump", description: "Return full transcript as plain text" },
  { name: "session", description: "Show session information", inputHint: "info|delete" },
  { name: "jobs", description: "Show background jobs" },
  { name: "transcript", description: "Browse the current session transcript" },
  { name: "context", description: "Show active context token usage breakdown" },
  { name: "usage", description: "Show token usage", inputHint: "[check]" },
  { name: "credential", description: "Switch or list stored credentials for this session", inputHint: "[selector]" },
  { name: "changelog", description: "Show release notes and changelog entries", inputHint: "[full|--full]" },
  { name: "tools", description: "Show available tools" },
  { name: "provider", description: "Set up API-compatible providers or login providers", inputHint: "add|login" },
  { name: "ssh", description: "Manage SSH connections", inputHint: "<subcommand>" },
  { name: "clear", description: "Clear context while preserving this session ID" },
  { name: "compact", description: "Compact the conversation", inputHint: "[focus instructions]" },
  { name: "handoff", description: "Generate a handoff document and start a new session", inputHint: "[focus instructions]" },
  { name: "contribute-pr", description: "Dump redacted session context and spawn a fresh contribute-pr worker", inputHint: "[focus instructions]" },
  { name: "star", description: "Star the current session for easier discovery" },
  { name: "unstar", description: "Remove the star from the current session" },
  { name: "memory", description: "Manage memory", inputHint: "<subcommand>" },
  { name: "rename", description: "Rename the current session", inputHint: "<title>" },
  { name: "login", description: "Login with OAuth provider", inputHint: "[provider|redirect URL]" },
  { name: "logout", description: "Logout from OAuth provider", inputHint: "[provider]" },
];

/** Aliases the adapter dispatches without advertising them in the menu. */
export const GJC_APP_BUILTIN_COMMAND_ALIASES: Readonly<Record<string, string>> = {
  "models": "model",
  "contribution-prep": "contribute-pr",
};

export const GJC_APP_BUILTIN_COMMAND_NAMES = new Set([
  ...GJC_APP_BUILTIN_COMMANDS.map((command) => command.name),
  ...Object.keys(GJC_APP_BUILTIN_COMMAND_ALIASES),
]);

/**
 * Bundled workflow skills, read from each SKILL.md frontmatter in the installed
 * runtime. Descriptions therefore match what the runtime actually ships.
 */
export const GJC_BUNDLED_SKILLS: readonly { name: string; description: string }[] = [
  { name: "autoresearch", description: "Goal-directed research missions that interleave web research with data experimentation and end on a structured best-effort verdict" },
  { name: "deep-interview", description: "Socratic deep interview with mathematical ambiguity gating before explicit execution approval" },
  { name: "ralplan", description: "Consensus planning entrypoint that auto-gates vague ultragoal requests before execution" },
  { name: "ultragoal", description: "Create and execute durable repo-native multi-goal plans over GJC goal mode artifacts." },
];
